### ISSUE TITLE
update link die

### ISSUE THREAD

**Issue by devme4f** [security-prince/PWK-OSCP-Preparation-Roadmap#1]
SMB enumeration with Kali Linux – enum4linux, acccheck and smbmap
https://hackercool.com/2016/07/smb-enumeration-with-kali-linux-enum4linuxacccheck-smbmap/ --> move permanently ->
https://www.hackercoolmagazine.com/smb-enumeration-with-kali-linux-enum4linuxacccheck-smbmap/

**Comment by security-prince** [comment]
Thank you @devme4f for pointing this out, fixed it https://github.com/security-prince/PWK-OSCP-Preparation-Roadmap/commit/9edcfaed5091e6c9d2dd01c945ad1502ef7a9174

Feel free to check the updated list [here](https://ishaqmohammed.me/posts/pwk-oscp-preparation-roadmap/)
